services:
  gitlab_web:
    container_name: gitlab-service
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.example.com:8929"
        gitlab_rails["gitlab_shell_ssh_port"] = 2224
        nginx["ssl_certificate"] = "/etc/ssl/certs/gitlab/cert.pem"
        nginx["ssl_certificate_key"] = "/etc/ssl/certs/gitlab/key.pem"
        # Add any other gitlab.rb configuration here, each on its own line
    hostname: gitlab.example.com
    image: gitlab/gitlab-ee:latest
    ports:
    - 8929:8929
    - '2224:22'
    restart: always
    shm_size: 256m
    volumes:
    - $GITLAB_HOME/config:/etc/gitlab
    - $GITLAB_SSL:/etc/ssl/certs/gitlab
    - $GITLAB_HOME/logs:/var/log/gitlab
    - $GITLAB_HOME/data:/var/opt/gitlab
  postgres_adminer:
    image: adminer
    ports:
    - 8080:8080
    restart: always
  postgres_db:
    container_name: postgres-db
    environment:
      POSTGRES_DB: name_here
      POSTGRES_PASSWORD: password_here
      POSTGRES_USER: username_here
    image: postgres:latest
    ports:
    - 5432:5432
    restart: always
